// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;

namespace WhamOnline.Models
{

    public class AppOptions : DotLiquid.Drop
    { 
        [JsonProperty("AppName")]
        public string AppName { get; set; }

        [JsonProperty("Platform")]
        public string Platform { get; set; }

        [JsonProperty("Theme")]
        public string Theme { get; set; }
    }

}
