// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using Newtonsoft.Json; 

namespace WhamOnline.Models
{ 
    public class Owner : DotLiquid.Drop
    { 
        [JsonProperty("Name")]
        public string Name { get; set; }

        [JsonProperty("Company")]
        public string Company { get; set; }

        [JsonProperty("email")]
        public string Email { get; set; }
    } 
}
