using System;
using System.Collections.Generic;
using Newtonsoft.Json;

// Generated by CS_ClassTemplate.dlq for Base.Address
namespace Wham.Base.Model
{
  public partial class Address 
  	
  {
    public static string CypherCreate {get; protected set;} = 
"MERGE (node:Address %_NODE_DATA_JSON_%)";

    public static string ToCypher(Address instance, string cypherTemplate){
    	var json = JsonConvert.SerializeObject(instance);
    	return cypherTemplate.Replace("%_NODE_DATA_JSON_%", json);
    }

      [JsonProperty("line1")]
    public string Line1 { get; set; }

    [JsonProperty("line2")]
    public string Line2 { get; set; }

    [JsonProperty("city")]
    public string City { get; set; }

    [JsonProperty("country")]
    public string Country { get; set; }

  
      }
}