using System;
using System.Collections.Generic;
using System.Dynamic;
using System.Linq;
using System.Text;
using System.Threading.Tasks; 
using Nancy;
using Newtonsoft.Json;
using WhamBase;
using Wham.Base.Nancy;
using Wham.Base.Model;

namespace Wham.Base.Nancy
{
    // Generated by NancyModule.dlq for Base.AddressCollection
    public partial class AddressCollectionModule 
    	: NancyModuleBase<AddressCollection>
    { 
        public AddressCollectionModule(){
            Hookup("/api/AddressCollection"); 
        }

        public AddressCollectionModule(IRepository<AddressCollection> repo) : this()
        {
            Repo = repo; 
        } 
    }
}
