using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks; 
using Nancy;
using Nancy.ModelBinding;
using Newtonsoft.Json; 
using WhamBase;

// Generated by NancyModuleDocBase.dlq
namespace Wham.Base.NancyDoc
{
	public partial class NancyModuleDocBase : NancyModule 
	{    
		public virtual string ViewResource { get; set; } = "index.html";

		public NancyModuleDocBase(){
			Hookup("/docs");
		}

		protected virtual void Hookup(string path)
		{ 
            Get[path] = _ => View[ViewResource ,_];  
		}
	} 
}