using System;
using System.Collections.Generic;
using System.Dynamic;
using System.Linq;
using System.Text;
using System.Threading.Tasks; 
using Nancy;
using Newtonsoft.Json;
using WhamBase;
using Wham.Base.NancyDoc;

namespace Wham.Base.NancyDoc
{
    // Generated by NancyModuleDocBase.dlq for Base.ShippingAddress
    public partial class ShippingAddressModuleDoc : NancyModuleDocBase
    { 
        public override string ViewResource
        {
            get
            {
                return "ShippingAddress.doc.html";
            } 
        }

        public ShippingAddressModuleDoc(){
            Hookup("/docs/ShippingAddress"); 
        } 
    }
}
